README.md, nghttpx.tmpl, nghttpx/main.go
=> Write nghttpx errorlog to the dedicated file rather than dumping it to pod log

controller.go
This commit changes upstream name format.  The default backend name is
now derived from actual default backend name.
=> Change upstream name format

README.md, examples/default-backend-svc.yaml, examples/default/rc-default.yaml
Great example for how to get nghttpx working. I've made some small changes that I struggled on while following the README as well as tweaking the example deployment configurations.
Also what do you think about trying to get [Let's encrypt](https://letsencrypt.org) working with for example [kube-lego](https://github.com/jetstack/kube-lego) like the nginx ingress is doing?
@tatsuhiro-t
=> Bootstrapping issues

Dockerfile, pkg/nghttpx/command.go
=> Configrevision

Dockerfile, default.tmpl, nghttpx.tmpl, pkg/cmd/main.go, pkg/controller/controller.go, pkg/nghttpx/command.go, pkg/nghttpx/main.go, pkg/nghttpx/template.go, pkg/nghttpx/types.go
=> Configurable ports

README.md, cmd/nghttpx-ingress-controller/main.go, pkg/controller/controller.go, pkg/controller/controller_test.go
This offers the same functionality of nginx ingress controller's
--publish-service flag.
Closes #65
=> Add --publish-service flag

README.md, nghttpx-backend.tmpl, pkg/controller/controller.go, pkg/nghttpx/types.go, pkg/nghttpx/utils.go, pkg/nghttpx/utils_test.go
Adds cookie-based affinity settings.
=> Add cookie-based session affinity support

.travis.yml
This will fix the issue that image cannot be pushed to docker hub.
=> travis: Remove -e option

Godeps/Godeps.json, README.md, pkg/controller/annotation.go, pkg/controller/annotation_test.go, vendor/github.com/ghodss/yaml/.travis.yml, vendor/github.com/ghodss/yaml/README.md, vendor/github.com/ghodss/yaml/fields.go, vendor/github.com/ghodss/yaml/yaml.go, vendor/github.com/ghodss/yaml/yaml_go110.go
Allow YAML in ingress.zlab.co.jp/backend-config annotation.
=> Yaml annotation

pkg/nghttpx/command.go
Garbage collect stale asset files
=> Delete stale asset files

Dockerfile, README.md, nghttpx-backend.tmpl, pkg/controller/controller.go, pkg/nghttpx/command.go, pkg/nghttpx/types.go, pkg/nghttpx/utils.go
Add per-backend mruby support which will be available in the next nghttp2 release (v1.33.0).
=> Per backend mruby

README.md, nghttpx-backend.tmpl, pkg/controller/annotation.go, pkg/controller/controller.go, pkg/nghttpx/command.go, pkg/nghttpx/mruby.go, pkg/nghttpx/mruby_test.go, pkg/nghttpx/types.go, pkg/nghttpx/utils.go, pkg/nghttpx/utils_test.go
This applies to affinity settings too, but they will be dealt with in
the later PR.
Amends #88
=> mruby script should be configured per host and path pattern

cmd/nghttpx-ingress-controller/main.go, pkg/controller/controller.go
This PR adds --deferred-shutdown-period flag which specifies how long the controller waits before actually starting shutting down.  In this period, the health check endpoint returns error.
=> Add deferred-shutdown-period flag

README.md, cmd/nghttpx-ingress-controller/main.go, pkg/controller/annotation.go, pkg/controller/controller.go, pkg/controller/controller_test.go
IngressClass support is automatically enabled if API server supports
IngressClass resource.
=> Add IngressClass support

Dockerfile, README.md, examples/default-backend.yaml, examples/proxyproto/01-default-backend.yaml, rc.yaml
and migrate to k8s-artifacts-prod registry.
=> Bump debian base

README.md, examples/default-backend.yaml, examples/proxyproto/01-default-backend.yaml, rc.yaml
This reverts commit c456f70a0f62b2ae2c29cbd97488fa986cd0f94a.
=> Revert "Migrate to k8s-artifacts-prod registry"

cmd/nghttpx-ingress-controller/main.go, examples/default/service-account.yaml, examples/proxyproto/02-nghttpx-rbac.yaml, pkg/controller/controller.go, rc.yaml
Introduce leader election.  Only leader updates Ingress status and
QUIC secrets.
=> Introduce leader election

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/util.go
Introduce LeaderController that has its own informers and listers,
performs the work for a leader.  It is started when the controller
starts leading, and stopped when it stops leading.  This fixes the
issue that some events might be missed when leader is changed.
=> Add LeaderController

cmd/nghttpx-ingress-controller/main.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/nghttpx/command.go, pkg/nghttpx/load_balancer.go, pkg/nghttpx/template.go, pkg/nghttpx/template_test.go, pkg/nghttpx/types.go
Rename Manager to LoadBalancer.  Interface is also renamed to
ServerReloader.
=> Rename Manager to LoadBalancer

pkg/controller/controller.go, pkg/controller/controller_test.go
Use SharedInformerFactory to start/stop informers as suggested by the documentation.
Replace SharedIndexInformers with Indexers and add comment that they are used for testing purpose.
=> Use SharedInformerFactory to start/stop informers

pkg/controller/controller.go, pkg/controller/controller_test.go
If EndpointSlice is enabled, which is default, get addresses from EndpointSlice when processing Service without selectors.
This removes the need to cache Endpoints when EndpointSlice is enabled.  This change also removes the watch filter by discoveryv1.LabelManagedBy for EndpointSlice to cache EndpointSlices which are not managed by endpointslice controller.  But that label selector is simply unnecessary for the general case because we just need EndpointSlices whatever manages it.
=> Get address from EndpointSlice when processing Service without selectors

pkg/nghttpx/nghttpx.tmpl, pkg/nghttpx/template_test.go
Make the following nghttpx options configurable:
- worker-process-grace-shutdown-period
- max-worker-processes
=> Make worker process options configurable

cmd/nghttpx-ingress-controller/main.go, pkg/controller/controller.go, pkg/nghttpx/nghttpx-backend.tmpl, pkg/nghttpx/nghttpx.tmpl, pkg/nghttpx/template.go, pkg/nghttpx/template_test.go, pkg/nghttpx/types.go
Add the following nghttpx process flags:
- --nghttpx-workers
- --nghttpx-worker-process-grace-shutdown-period
- --nghttpx-max-worker-processes
=> Add nghttpx process flags

Dockerfile, patches/0001-nghttpx-Fix-bug-that-causes-400-response-after-upgra.patch, patches/nghttpx-reload.patch
Add the following upstream nghttpx patches:
- https://github.com/nghttp2/nghttp2/pull/1874
- https://github.com/nghttp2/nghttp2/pull/1880
- https://github.com/nghttp2/nghttp2/pull/1881
=> Add nghttpx patches

.github/workflows/build.yaml
Bump setup-go to v4, and get go version from go.mod.
=> Bump setup-go to v4

pkg/controller/controller.go
This fixes the bug that controller takes long time to exit.
=> Shutdown syncQueue

cmd/nghttpx-ingress-controller/main.go, examples/default/service-account.yaml, examples/proxyproto/02-nghttpx-rbac.yaml, pkg/controller/controller.go, pkg/controller/controller_test.go, rc.yaml
EndpointSlice is always used regardless of endpoint-slices flag.
=> Remove Endpoints resource support

pkg/nghttpx/command.go
Fix error message by deleting a repeated 'to'.
=> Fix error message

pkg/controller/util.go
Fix the bug in podLabelSelector that does not remove labels correctly.
=> Fix podLabelSelector

cmd/nghttpx-ingress-controller/main.go, pkg/util/flags/flags.go, pkg/util/flags/flags_test.go
Add NamespacedName flag to add extra validations and remove repetitive processing of command-line flags that take namespace/name form.
=> Add NamespacedName flag
