zlabjp/nghttpx-ingress-lb

- Dockerfile
This is nghttpx bug, and we patched nghttp2 v1.17.0 with the relevant
commit.
Fixes #4
> Fix bug that leaves defunct process on reload

- default.conf
Add logging options to default configuration because we don't want to write them to pod log.
Access log may be interesting since we might want to see which requires are rejected in this phase.
> Add default logging configuration

- pkg/controller/controller.go
- pkg/nghttpx/nghttpx.go
Sort TLSCred by its key so that we can expect same order of TLSCred.
> Sort TLSCred by its key

- README.md
- nghttpx-backend.tmpl
- pkg/controller/controller.go
- pkg/controller/util.go
- pkg/nghttpx/types.go
Fixes #17 
Note that dns parameter might not work without upgrading nghttpx to v1.18.1.
> More port bakend config

- pkg/controller/controller.go
- pkg/nghttpx/utils.go
This fixes the issue that nghttpx refuses to reload configuration
because of invalid affinity parameter (missing value) if ConfigMap is
not used.
Fixes #21
> Fix missing default value in PortBackendConfig

- pkg/cmd/main.go
- pkg/controller/controller.go
- pkg/nghttpx/command.go
- pkg/nghttpx/main.go
When controller gets SIGTERM signal, SIQUIT signal is sent to nghttpx
master process to make it shut down gracefully.  Controller now exits
when nghttpx finishes without waiting for pod deletion
> Gracefully shut down nghttpx

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Remove named port annotation (ingress.kubernetes.io/named-ports).
Instead, lookup named port in Pod spec directly.
Fixes #27
> Remove named port annotation

- pkg/controller/controller.go
- pkg/nghttpx/command.go
- pkg/nghttpx/main.go
Previously, we apply throttling on CheckAndReload function.  It means
that we most likely use older configuration.  In this commit, we apply
throttling on sync function, and use latest configuration if possible.
Since the controller always uses all available information, it is not
necessary to enqueue the object key which has some events.  Therefore,
we use the same key for all events.
Fixes #26
> Use single sync key, and apply throttling on sync function

- README.md
- nghttpx-backend.tmpl
- pkg/cmd/main.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/nghttpx/types.go
> Redirect to https URI if Ingress contains TLS, and service is accessed via cleartext HTTP

- README.md
- pkg/controller/controller.go
- pkg/controller/controller_test.go
If Ingress.Spec.Backend is specified, it replaces the default backend
given in the command-line flag.  The backend-config annotation works
as usual.
> Support Ingress.Spec.Backend

- README.md
- nghttpx.tmpl
- pkg/controller/controller_test.go
- pkg/nghttpx/command.go
- pkg/nghttpx/types.go
- pkg/nghttpx/utils.go
The controller looks for nghttpx-mruby-file-content key in ConfigMap.
Its associated string is used as a mruby script, and it is referenced
by mruby-file option from the configuration file.
Fixes #29
> Add mruby file support

- Dockerfile
- cmd/nghttpx-ingress-controller/main.go
- nghttpx.tmpl
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/nghttpx/command.go
- pkg/nghttpx/main.go
- pkg/nghttpx/template.go
- pkg/nghttpx/tls.go
- pkg/nghttpx/tls_test.go
- pkg/nghttpx/types.go
- pkg/nghttpx/utils.go
The following flags are added:
* --nghttpx-conf-dir: path to nghttpx configuration directory.
* --nghttpx-exec-path: path to nghttpx executable.
* --nghttpx-http-port: port to listen to for HTTP requests.
* --nghttpx-https-port: port to listen to for HTTPS requests.
This commit also fixes the potential race that the default
configuration file is overwritten by the new configuration file while
nghttpx is reading the default one.
> Add flags to run nghttpx contorller outside cluster

- examples/custom-configuration/rc-custom-configuration.yaml
- examples/daemonset/as-daemonset.yaml
- examples/default/rc-default.yaml
- rc.yaml
Because CNI cannot handle hostPort at the moment, we have to use
hostNetwork in order to workaround it.
Fixes #48
> Make use of hostNetwork

- Dockerfile
There is a new release available.
Fixes: https://github.com/zlabjp/nghttpx-ingress-lb/issues/58
See: https://github.com/nghttp2/nghttp2/releases
> Upgrade to nghttp2 v1.26.0

- README.md
- cmd/nghttpx-ingress-controller/main.go
- examples/proxyproto/00-loadbalancer.yaml
- examples/proxyproto/01-default-backend.yaml
- examples/proxyproto/02-nghttpx-rbac.yaml
- examples/proxyproto/03-nghttpx.yaml
- examples/proxyproto/README.md
- nghttpx.tmpl
- pkg/controller/controller.go
- pkg/nghttpx/types.go
Fixes https://github.com/zlabjp/nghttpx-ingress-lb/issues/59
The proxyproto param enables the PROXY protocol for all frontends,
which are public-facing, i.e. the API- and HEALTH frontend are ignored.
The definition of how to enable the PROXY protocol can be found in:
https://nghttp2.org/documentation/nghttpx-howto.html#enable-proxy-protocol
> Add `proxyproto` flag.

- README.md
- pkg/controller/annotation.go
- pkg/controller/annotation_test.go
- pkg/controller/controller.go
- pkg/nghttpx/types.go
- pkg/nghttpx/utils.go
- pkg/nghttpx/utils_test.go
default-backend-config annotation provides a default value of missing
backend-config per field basis.
For example, if a pair of service and port has a following backend-config:
{"affinity": "ip"}
And if default-backend-config looks like so:
{"proto": "h2"}
The final backend-config for the service and port becomes like so:
{"proto": "h2", "affinity": "ip"}
Fixes #63
> Add default-backend-config annotation

- Dockerfile
This reduces image size down to 109MiB from 227MiB.
debian-base image is maintained at
https://github.com/kubernetes/kubernetes/tree/master/build/debian-base
Fixes #71
> Use debian-base as base image

- pkg/nghttpx/types.go
The document says that if affinityCookieSecure is set to empty string,
it defaults to "auto".  But previously the code just leaves it as is,
and nghttpx rejects it.  This commit makes sure that empty
affinityCookieSecure defaults to "auto".
> Make affinityCookieSecure default to "auto"

- Dockerfile
OpenSSL 1.1.1 is available in the base image, so we don't need to
build one by ourselves.
> Bump debian-base image

- Dockerfile
- image/var/log/nghttpx/.gitignore
- static.patch
Build nghttpx statically and use multi stage build to copy only
required files to runtime distroless/cc image which cuts image size to
half.  From this commit, only nghttpx binary is included.  Other
binaries which are included in the old images (e.g., h2load, nghttp
etc) are not included in new image.
> Build nghttpx statically and use distroless image to shrink image

- cmd/nghttpx-ingress-controller/main.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Add no-default-backend-override flag to ignore settings or rules in
Ingress resource which override default backend service.
> Add no-default-backend-override flag

- 0001-Allow-percent-encoded-in-backend-pattern.patch
- Dockerfile
- pkg/controller/controller.go
nghttpx does not allow ':' in pattern although it is a valid character
in URI path.  This commit includes a patch to instruct nghttpx to
recognized %3a (which is percent-encoded form of ':') as ':' in
pattern.  The change in Ingress controller code performs
percent-encoding against ':' so that this process is transparent to
users.
> Allow ':' in HTTP path

- README.md
- cmd/nghttpx-ingress-controller/main.go
- examples/ingress.yaml
- pkg/controller/annotation.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Migrate to networkingv1.Ingress.  The "kubernetes.io/ingress.class"
annotation support has been removed.  --ingress-class flag is also
deprecated.  IngressClass is enabled by default.
> Migrate to networkingv1.Ingress

- Dockerfile
- pkg/nghttpx/nghttpx.tmpl
rlimit-memlock is not necessary anymore with libbpf >= v0.7.0 strict
mode.
> Bump dependencies to make build succeed

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/nghttpx/nghttpx.tmpl
- pkg/nghttpx/template_test.go
- pkg/nghttpx/tls.go
- pkg/nghttpx/tls_test.go
- pkg/nghttpx/types.go
Use checksum as TLS key and certificate file name so that we can
remove checksum from the configuration file comment and only pass the
unique pairs of TLS private key, certificate, and optionally OCSP
response.
> Use checksum as TLS key and certificate file name

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/util.go
Rewrite Ingress status update, and now Ingress status is updated when
changes are detected per single Ingress resource rather than updating
them all periodically.  Now we do not delete LoadBalancerIngress when
Ingress Pod exits because in practice at least one Ingress controllers
continue to run, and if new class of Ingress controller takes control
of the existing Ingress resource, it will overwrite
LoadBalancerIngress with its own.
> Rewrite Ingress status update

- cmd/nghttpx-ingress-controller/main.go
- pkg/nghttpx/command.go
- pkg/nghttpx/load_balancer.go
Previously, there is a race condition that asset files being used are deleted if backend is reloaded too quickly.  This commit changes the way of deleting asset files by checking its modification time, and if it is too old, the file is deleted.  New flag, stale-assets-threshold, is added to control this threshold.
> Delete asset files by checking its modification time

- README.md
- cmd/nghttpx-ingress-controller/main.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/nghttpx/command.go
- pkg/nghttpx/nghttpx.tmpl
- pkg/nghttpx/template_test.go
- pkg/nghttpx/tls.go
- pkg/nghttpx/tls_test.go
- pkg/nghttpx/types.go
Share TLS ticket keys among nghttpx-ingress-controllers via Secret, which enables stable TLS session resumption.
> Share TLS ticket keys

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/nghttpx/quic.go
- pkg/nghttpx/quic_test.go
Now new key is placed at the end of QUIC keying materials.  It is not used for encryption immediately, and starts encrypting data on the next rotation, as we did for TLS ticket key.  This is a backward incompatible change.  There is no migration from the previous release because HTTP/3 is experimental.
> Revise QUIC keying materials in backward incompatible way

- .github/workflows/build.yaml
Now go line in go.mod requires patch version.  go line indicates the minimum go version that this module requires.  Meanwhile, previously we set go line without patch version.  go-version-file of setup-go looks go line and picks the latest go patch version.  But now it includes patch version, setup-go always picks the exact version that go line specifies, which is not what we want.  As a workaround, stop using go-version-file, and use go-version.
> Workaround incompatibility between go1.21+ go line and setup-go

- Dockerfile
The 'as' keyword should match the case of the 'from' keyword
> Fix docker lint warning

- README.md
- go.mod
- pkg/nghttpx/utils.go
Get rid of unmaintained go-difflib, and use go-cmp instead.  go-cmp is not a drop-in replacement because the output differs.  But the main goal here is to show the differences between the configurations, and it can be achieved with go-cmp as well.
> Replace go-difflib with go-cmp
